name: Deploy Landing Page

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            cd /var/www/Amienn-landing
            git fetch origin main
            git reset --hard origin/main
            docker build --no-cache -t aamenn-landing:latest -f Dockerfile .
            docker stop aamenn-landing || true
            docker rm aamenn-landing || true
            docker run -d \
              --name aamenn-landing \
              --network aamenn-backend_default \
              -p 8082:8082 \
              --restart unless-stopped \
              aamenn-landing:latest
            echo "Deployment complete"
